### ISSUE TITLE
Use Plaform.OS === 'web' in common

### ISSUE THREAD

**Issue by matt-eaton** [benawad/react-native-web-series#16]
Hi @benawad  thx for the series it's super helpful. I was wondering if in the common package you check the "web" platform. I could be understanding this wrong but I think react-native-web provides that functionality and I don't see it included in the common package. 

Hopefully I can answer this myself soon. I'm in the process of trying to get everything setup, but I'm little new in this space.

Thanks again.

**Comment by benawad** [comment]
Platform.OS is coming from react native, but the value of it will be 'web' when used in react-native-web projects

**Comment by matt-eaton** [comment]
Ah I see that makes sense. Since common is included and run inside a react-native-web project the value of "web" will be available.  It sounds kinda obvious once you say it out loud.

Thanks again love your videos.
