### ISSUE TITLE
Hooks error

### ISSUE THREAD

**Issue by adaxing** [benawad/react-native-web-series#7]
After implementing common folder, in web folder set dependencies "@wow/common": "1.0.0", and install @wow/common packages. Fix App.tsx file to import App from '@wow/common'. Then start to yarn start the web server, it turns to error
> "Hooks can only be called inside the body of a function component"

By the way, i was watching video from YouTube, and followed exact what you did. I really don't know what happened, really appreciate your help.

.

**Comment by benawad** [comment]
I think that usually occurs when there are multiple versions of react installed. Make sure you have the same version of react across both packages then try removing node_modules and reinstalling

**Comment by adaxing** [comment]
Thanks!! I figured it out.
