### ISSUE TITLE
 '@wow/common@1.0.0' is not in the npm registry

### ISSUE THREAD

**Issue by shreyansh073** [benawad/react-native-web-series#9]
I get this error on running npm install in /packages/app. Can you please release the package or suggest a solution to this? TIA!

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@wow%2fcommon - Not found
npm ERR! 404 
npm ERR! 404  '@wow/common@1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'app'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by benawad** [comment]
try `yarn install` instead of npm

**Comment by shreyansh073** [comment]
Works. Thanks.
